### ISSUE TITLE
Vignette examples are not working. Example code 1 returning $ atomic vector error

### ISSUE THREAD

**Issue by KrishnaTO** [paulrougieux/FAOSTATpackage#4]
Hi, 
Upon running the 1st example from the vignette, 
```
## ----FAO-search, eval=FALSE---------------------------------------------------
#  ## Use the interective function to search the codes.
#  FAOsearch()
#  
#  ## Use the result of the search to download the data.
#  test = getFAO(query = .LastSearch)
```
Returned:
`Error: $ operator is invalid for atomic vectors`

**Comment by paulrougieux** [comment]
Thanks yes for sure the FAOSTAT API on which this package was based has changed in 2017 and this package hasn't been working since then. I will fix more in this summer 2020. 

The main interest of this package lies in the updated functions to download data from the bulk download: 

    download_faostat_bulk
    read_faostat_bulk

And in the mapping tables: 

    FAOcountryProfile
    FAOmetaTable
    FAOregionProfile

Look at the help of those functions and data sets for more information. 

Otherwise there is also @muuankarski 's take on the FAOSTAT bulk download here:
https://github.com/muuankarski/faobulk
He created functions to parse the FAOSTAT xml files, I might include them at some point here.

**Comment by paulrougieux** [comment]
@KrishnaTO thanks anyway for reporting and please report more issues concerning the bulk download functions and other parts of the package. Also you are welcomed to suggest updates to the vignettes.

**Comment by KrishnaTO** [comment]
> @KrishnaTO thanks anyway for reporting and please report more issues concerning the bulk download functions and other parts of the package. Also you are welcomed to suggest updates to the vignettes.

Thanks for updating the readme to reflect this.

**Comment by paulrougieux** [comment]
This was reported by another user. Re-open and change title.

**Comment by paulrougieux** [comment]
In this commit I documented the new bulk download method. Further work on the vignette needed, but at least the data download should be working now.

https://github.com/paulrougieux/FAOSTATpackage/commit/48806cab413e9dd55f407dd8e3316ec1827c052c

**Comment by paulrougieux** [comment]
Dear Kirschna,
Could you kindly share a working example of your current use of the FAOSTAT
download functions, I'd like to collect working examples here to update the
demo:

https://gitlab.com/paulrougieux/faostatpackage/-/issues/2

Regards,
Paul

**Comment by KrishnaTO** [comment]
Hi Paul, 

Added demo of the method I used was through the reworked FAOSearch function (now in new pull request #6 )

Cheers,
Krishna
